name: Deploy Storybook

on: [pull_request]

permissions:
  pull-requests: write
  contents: write

jobs:
  deploy:
    env:
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    timeout-minutes: 10
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22

        # Node.jsのインストール
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build storybook
        run: pnpm run build:story
        
      - name: Run test
        run: pnpm run test:storybook
